//
//  DefaultsContainer.swift
//  Stepic
//
//  Created by Alexander Karpov on 07.04.17.
//  Copyright © 2017 Alex Karpov. All rights reserved.
//

import Foundation

/*
 Used to store application data, generated by an app
 */
final class DefaultsContainer {
    static let launch = LaunchDefaultsContainer()
    static let explore = ExploreDefaultsContainer()

    private init() { }
}
