a/b:
  - changed-files:
      - any-glob-to-any-file:
          [
            "Stepic/Legacy/Analytics/SplitTests/*",
            "Stepic/Legacy/Analytics/SplitTests/**/*",
          ]

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          ["Gemfile", "Gemfile.lock", "Podfile", "Podfile.lock"]

ci/cd:
  - changed-files:
      - any-glob-to-any-file:
          [
            ".github/workflows/**",
            ".github/actions/**",
            ".github/dependabot.yml",
            ".github/filters.yaml",
            ".github/labeler.yml",
          ]

main:
  - changed-files:
      - any-glob-to-any-file: ["Stepic/*", "Stepic/**/*"]

release:
  - base-branch: "master"
