a/b:
  - changed-files:
      - any-glob-to-any-file:
          [
            "Stepic/Legacy/Analytics/SplitTests/*",
            "Stepic/Legacy/Analytics/SplitTests/**/*",
          ]

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          ["Gemfile", "Gemfile.lock", "Podfile", "Podfile.lock"]

main:
  - changed-files:
      - any-glob-to-any-file: ["Stepic/*", "Stepic/**/*"]

release:
  - base-branch: "master"
