warning_threshold: 15

indentation: 4

analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

only_rules:
  - anyobject_protocol
  - attributes
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - compiler_protocol_init
  - computed_accessors_order
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - control_statement
  - convenience_type
  - deployment_target
  - discarded_notification_center_observer
  - discouraged_direct_init
  - discouraged_none_name
  - discouraged_object_literal
  - duplicate_enum_cases
  - duplicate_imports
  - duplicated_key_in_dictionary_literal
  - dynamic_inline
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - fallthrough
  - fatal_error_message
  - file_header
  - file_length
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - generic_type_name
  - identical_operands
  - identifier_name
  - implicit_getter
  - implicit_return
  - implicitly_unwrapped_optional
  - inert_defer
  - is_disjoint
  - joined_default_parameter
  - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_multiple
  - legacy_nsgeometry_functions
  - legacy_random
  - line_length
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - mark
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
  - nesting
  - nimble_operator
  - no_space_in_method_call
  - nslocalizedstring_key
  - nsobject_prefer_isequal
  - number_separator
  - object_literal
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  # - prohibited_nan_comparison
  - prefer_self_type_over_type_of_self
  - prefixed_toplevel_constant
  - private_over_fileprivate
  - private_unit_test
  - prohibited_interface_builder
  - prohibited_super_call
  - protocol_property_accessors_order
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_boolean
  - reduce_into
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_type_annotation
  - redundant_void_return
  # - return_value_from_void_function
  - return_arrow_whitespace
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - statement_position
  - static_operator
  - strong_iboutlet
  - switch_case_alignment
  - switch_case_on_newline
  - syntactic_sugar
  - superfluous_disable_command
  - toggle_bool
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  # - tuple_pattern
  - type_name
  - unavailable_function
  - unneeded_break_in_switch
  - unowned_variable_capture
  - unused_capture_list
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_optional_binding
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  # - void_function_in_ternary
  - void_return
  - weak_delegate
  - yoda_condition

# settings
anyobject_protocol:
  severity: error

attributes:
  severity: error

block_based_kvo:
  severity: error

class_delegate_protocol:
  severity: error

closing_brace:
  severity: error

closure_spacing:
  severity: error

colon:
  severity: error

comma:
  severity: error

compiler_protocol_init:
  severity: error

computed_accessors_order:
  severity: error
  order: get_set

conditional_returns_on_newline:
  severity: error

contains_over_filter_count:
  severity: error

contains_over_filter_is_empty:
  severity: error

contains_over_first_not_nil:
  severity: error

contains_over_range_nil_comparison:
  severity: error

control_statement:
  severity: error

convenience_type:
  severity: error

deployment_target:
  severity: error

discarded_notification_center_observer:
  severity: error

discouraged_direct_init:
  severity: error

discouraged_none_name:
  severity: warning

discouraged_object_literal:
  severity: error

duplicate_enum_cases:
  severity: error

duplicate_imports:
  severity: error

duplicated_key_in_dictionary_literal:
  severity: error

dynamic_inline:
  severity: error

empty_collection_literal:
  severity: error

empty_count:
  severity: error

empty_enum_arguments:
  severity: error

empty_parameters:
  severity: error

empty_parentheses_with_trailing_closure:
  severity: error

empty_string:
  severity: error

empty_xctest_method:
  severity: error

enum_case_associated_values_count:
  warning: 4
  error: 5

explicit_self:
  severity: error

fallthrough:
  severity: error

file_header:
  forbidden_pattern: "^//[^/]|/\\*[^*]"

file_length:
  warning: 400
  error: 400
  ignore_comment_only_lines: true

file_name_no_space:
  severity: error

first_where:
  severity: error

flatmap_over_map_reduce:
  severity: error

for_where:
  severity: error

force_cast:
  severity: error

force_try:
  severity: error

force_unwrapping:
  severity: error

identical_operands:
  severity: error

generic_type_name:
  severity: error

identifier_name:
  severity: error
  excluded: ["i", "j", "x", "y", "z", "id", "to", "vk", "h1", "h2", "h3", "r", "g", "b", "no"]
  max_length: 64

implicit_getter:
  severity: error

implicit_return:
  severity: error

implicitly_unwrapped_optional:
  severity: error

is_disjoint:
  severity: error

large_tuple:
  warning: 3
  error: 3

last_where:
  severity: error

legacy_cggeometry_functions:
  severity: error

legacy_constant:
  severity: error

legacy_constructor:
  severity: error

legacy_hashing:
  severity: error

legacy_multiple:
  severity: error

legacy_nsgeometry_functions:
  severity: error

line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_comments: true
  ignores_interpolated_strings: true

lower_acl_than_parent:
  severity: error

mark:
  severity: error

modifier_order:
  severity: error

multiline_arguments:
  severity: error
  first_argument_location: next_line

multiline_arguments_brackets:
  severity: error

multiline_literal_brackets:
  severity: error

multiline_parameters:
  severity: error

multiline_parameters_brackets:
  severity: error

multiple_closures_with_trailing_closure:
  severity: error

nesting:
  # for dataflow
  type_level: 3

number_separator:
  minimum_length: 6

object_literal:
  severity: error
  image_literal: false
  color_literal: false

opening_brace:
  severity: error

operator_usage_whitespace:
  severity: error

operator_whitespace:
  severity: error

optional_enum_case_matching:
  severity: error

overridden_super_call:
  severity: error

prefer_self_type_over_type_of_self:
  severity: error

prefixed_toplevel_constant:
  severity: error

prohibited_super_call:
  severity: error

prohibited_interface_builder:
  severity: error

reduce_boolean:
  severity: error

redundant_set_access_control:
  severity: error

redundant_type_annotation:
  severity: error

statement_position:
  severity: error

static_operator:
  severity: error

switch_case_alignment:
  severity: error

switch_case_on_newline:
  severity: error

syntactic_sugar:
  severity: error

trailing_comma:
  severity: error

trailing_newline:
  severity: error

trailing_semicolon:
  severity: error

# tuple_pattern:
#  severity: error

type_name:
  severity: error
  max_length: 64

unneeded_break_in_switch:
  severity: error

unowned_variable_capture:
  severity: error

unused_enumerated:
  severity: error

unused_import:
  require_explicit_imports: true
  allowed_transitive_imports:
    - module: Foundation
      allowed_transitive_imports:
        - CoreFoundation
        - Darwin
        - ObjectiveC
        
unused_optional_binding:
  severity: error

vertical_whitespace_closing_braces:
  severity: error

vertical_whitespace_opening_braces:
  severity: error

void_return:
  severity: error

weak_delegate:
  severity: error