warning_threshold: 15

indentation: 4

included:
  - Stepic/Sources

analyzer_rules:
  - explicit_self
  - unused_private_declaration

whitelist_rules:
  - array_init
  - attributes
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - control_statement
  - cyclomatic_complexity
  - deployment_target
  - discarded_notification_center_observer
  - discouraged_direct_init
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - duplicate_imports
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_string
  - fallthrough
  - fatal_error_message
  - first_where
  - file_length
  - file_header
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - generic_type_name
  - identical_operands
  - identifier_name
  - implicit_getter
  - implicit_return
  - implicitly_unwrapped_optional
  - inert_defer
  - is_disjoint
  - joined_default_parameter
  - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - line_length
  - literal_expression_end_indentation
  - mark
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
  - nesting
  - notification_center_detachment
  - nslocalizedstring_key
# available in master version only now
#  - nsobject_prefer_isequal
  - number_separator
  - object_literal
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - private_over_fileprivate
  - prohibited_interface_builder
  - prohibited_super_call
  - protocol_property_accessors_order
# available in master version only now
#  - reduce_boolean
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_type_annotation
  - redundant_void_return
  - return_arrow_whitespace
  - shorthand_operator
  - sorted_first_last
  - sorted_imports
  - statement_position
  - static_operator
  - switch_case_alignment
  - switch_case_on_newline
  - syntactic_sugar
  - superfluous_disable_command
  - toggle_bool
  - trailing_semicolon
  - trailing_whitespace
  - trailing_comma
  - type_name
  - unavailable_function
  - unneeded_break_in_switch
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_optional_binding
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - void_return
  - weak_computed_property
  - weak_delegate
  - yoda_condition

# settings
mark:
  severity: error

opening_brace:
  severity: error

vertical_whitespace_closing_braces:
  severity: error

vertical_whitespace_opening_braces:
  severity: error

statement_position:
  severity: error

conditional_returns_on_newline:
  severity: error

trailing_semicolon:
  severity: error

control_statement:
  severity: error

weak_delegate:
  severity: error

colon:
  severity: error

comma:
  severity: error

force_cast:
  severity: error

force_try:
  severity: error

force_unwrapping:
  severity: error

switch_case_alignment:
  severity: error

switch_case_on_newline:
  severity: error

attributes:
  severity: error

multiline_arguments_brackets:
  severity: error

multiline_literal_brackets:
  severity: error

multiline_parameters:
  severity: error

multiline_parameters_brackets:
  severity: error

multiple_closures_with_trailing_closure:
  severity: error

operator_usage_whitespace:
  severity: error

operator_whitespace:
  severity: error

closure_spacing:
  severity: error

identifier_name:
  severity: error
  excluded: ["i", "j", "x", "y", "z", "id", "to"]

type_name:
  severity: error
  max_length: 64

generic_type_name:
  severity: error

syntactic_sugar:
  severity: error

void_return:
  severity: error

implicitly_unwrapped_optional:
  severity: error

unused_optional_binding:
  severity: error

class_delegate_protocol:
  severity: error

empty_enum_arguments:
  severity: error

unneeded_break_in_switch:
  severity: error

fallthrough:
  severity: error

redundant_type_annotation:
  severity: error

explicit_self:
  severity: error

modifier_order:
  severity: error

redundant_set_access_control:
  severity: error

prohibited_interface_builder:
  severity: error

nesting:
  # for dataflow
  type_level: 3

file_length:
  warning: 400
  error: 400
  ignore_comment_only_lines: true

large_tuple:
  warning: 3
  error: 3

line_length:
  warning: 120
  error: 120
  ignores_urls: true
  ignores_comments: true
  ignores_interpolated_strings: true

multiline_arguments:
  severity: error
  first_argument_location: next_line

number_separator:
  minimum_length: 6

object_literal:
  severity: error
  image_literal: false
  color_literal: false

file_header:
  forbidden_pattern: "^//[^/]|/\\*[^*]"